default_language_version:
    python: python3.11
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: check-toml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.287
      hooks:
          - id: ruff
            args:
                - --fix
    - repo: local
      hooks:
        - id: mypy
          name: mypy
          # or `entry: poetry run mypy`, but perhaps both are the same
          entry: mypy
          require_serial: true
          # From the docs it is not clear the difference between `language: python` VS `language: system`
          language: system
          types: [ python ]
