version: "3.9"
services:
  app:
    build: .
    environment:
      - POSTGRESQL_DSN=postgresql://postgres:postgres@postgres:5432/homefinancier
      - GRPC_HOST=[::]
      - GRPC_PORT=80
    depends_on:
      - postgres
    ports:
      - 80:80

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
