version: "3.9"
services:
  app:
    build:
      context: ./../
      dockerfile: ./deployment/dockerfiles/homefinancier.Dockerfile
    container_name: homefinancier_app
    environment:
      - GRPC_HOST=[::]
      - GRPC_PORT=80
      - POSTGRESQL_DSN=postgresql://postgres:postgres@host.docker.internal:5432/homefinancier
    depends_on:
      - postgres
    ports:
      - 80:80

  postgres:
    image: postgres:16
    container_name: homefinancier_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
