version: "3.9"
services:
  app:
    build:
      context: ./../
      dockerfile: ./deployment/dockerfiles/homefinancier.Dockerfile
    container_name: homefinancier_app
    env_file: ./../.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: homefinancier_postgres
    env_file: ./../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
