name: Deploy

on:
  workflow_run:
    workflows: ["Quality Check"]
    types:
      - completed
    branches:
      - main

jobs:
  on-success:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using ssh & docker-compose
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd HomeFinancier/deployment
            docker-compose stop
            docker-compose rm -f
            git pull
            docker-compose up -d --build
